# Unilaterally Allowed Utilities
# ==============================

[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  ^(\
  cat\
  |find\
  |grep\
  |head\
  |ls\
  |pwd\
  |readlink\
  |tail\
  |which\
  |whoami\
  )\
  [^;|&<>]*$\
"""
decision = "allow"
priority = 100

# Partially allowed commands
# ==========================

# Git
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  ^git (\
  branch\
  |diff\
  |log\
  |remote\
  |show\
  |status\
  |worktree list\
  )\
  [^;|&<>]*$\
"""
decision = "allow"
priority = 100

# Tmux
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  ^tmux (\
  list-sessions\
  |list-windows\
  |ls\
  )\
  [^;|&<>]*$\
"""
decision = "allow"
priority = 100

# NPM / Node
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  ^npm (\
  --version\
  |run test\
  |test\
  )\
  [^;|&<>]*$\
"""
decision = "allow"
priority = 100

# Allow free access to pixel 7
[[rule]]
toolName = "run_shell_command"
#commandPrefix = "adb -s 28271FDH3005RK"
commandRegex = """\
  ^adb (devices|-s 28271FDH3005RK)[^;|&<>]*$\
"""
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  ^(flutter|/snap/bin/flutter) (\
  --version\
  |build\
  |devices\
  |test\
  )\
  [^;|&<>]*$\
"""
decision = "allow"
priority = 100
