# Unilaterally Allowed Utilities
# ==============================
# commandRegex should NOT use ^ and $ anchors because the policy
# engine splits commands into a JSON string for evaluation:
# https://geminicli.com/docs/reference/policy-engine/#toml-rule-schema`

[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  (\
  cat\
  |find\
  |grep\
  |head\
  |ls\
  |pwd\
  |readlink\
  |tail\
  |which\
  |whoami\
  )\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100

# Partially allowed commands
# ==========================

# git
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  git (\
  branch\
  |diff\
  |log\
  |remote\
  |show\
  |status\
  |worktree list\
  )\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100

# tmux
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  tmux (\
  list-sessions\
  |list-windows\
  |ls\
  )\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100

# npm / node
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  npm (\
  --version\
  |run test\
  |test\
  )\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100

# Allow free access to pixel 7
[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  adb (devices|-s 28271FDH3005RK)\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
commandRegex = """\
  (flutter|/snap/bin/flutter) (\
  --version\
  |build\
  |devices\
  |test\
  )\
  [^;|&<>]*\
"""
decision = "allow"
priority = 100
